on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.riccardozocche.com
        username: developer@riccardozocche.com
        server-dir: public_html/wp-content/themes/riccardozocche/
        password: ${{ secrets.FTP_PASSWORD }}
