on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.riccardozocche.com
        username: 
        server-dir: public_html/wp-content/themes/francescobertele/
        password: ${{ secrets.FTP_PASSWORD }}
